/**
 * Run every case in vectors/booklet.json through the TypeScript engine and
 * compare every field in `expect`. The vectors are generated by the Python
 * reference; this is the contract between the two engines. Do not proceed
 * past a failure by adjusting a vector.
 */
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { runCase, type CaseSpec } from "../index";

const HERE = dirname(fileURLToPath(import.meta.url));
const VECTORS = resolve(HERE, "../../../../vectors/booklet.json");
/** Reviewer disagreements converted by api/to_vectors.py (Task 4.3). Optional. */
const REVIEWER = resolve(HERE, "../../../../vectors/reviewer.json");

interface Case extends CaseSpec {
  id: string;
  page: number | null;
  source: string;
  expect: Record<string, unknown>;
  booklet_says: unknown;
  note: string;
}

const doc = JSON.parse(readFileSync(VECTORS, "utf8")) as { cases: Case[] };
const reviewer = existsSync(REVIEWER)
  ? (JSON.parse(readFileSync(REVIEWER, "utf8")) as { cases: Case[] })
  : { cases: [] };
const indent = (s: string) => s.split("\n").map((l) => "    " + l).join("\n");

describe(`vectors/booklet.json (${doc.cases.length} cases)`, () => {
  it("has at least 30 cases, every one with a non-empty expect", () => {
    expect(doc.cases.length).toBeGreaterThanOrEqual(30);
    for (const c of doc.cases) expect(Object.keys(c.expect).length, c.id).toBeGreaterThan(0);
  });

  it.each(doc.cases.map((c) => [c.id, c] as const))("%s", (_id, c) => {
    const actual = runCase(c).expect;
    const mismatches: string[] = [];
    for (const k of Object.keys(c.expect)) {
      const want = JSON.stringify(c.expect[k]);
      const got = JSON.stringify(actual[k]);
      if (want !== got) mismatches.push(`  ${k}:\n    expected ${want}\n    actual   ${got}`);
    }
    if (mismatches.length) {
      const page = c.page === null ? "no page" : `p.${c.page}`;
      const report = [
        `VECTOR FAILED ${c.id} (${page}, source ${c.source})`,
        c.note ? `  note: ${c.note}` : "",
        ...mismatches,
        "  TypeScript working:",
        indent(typeof actual.render === "string" ? actual.render : "(no working)"),
        "  Python working:",
        indent(String(c.expect.render ?? "(none)")),
      ].filter(Boolean).join("\n");
      console.error(report);
      expect.fail(report);
    }
  });
});

describe.runIf(reviewer.cases.length > 0)(`vectors/reviewer.json (${reviewer.cases.length} reviewer cases)`, () => {
  it.each(reviewer.cases.map((c) => [c.id, c] as const))("%s", (_id, c) => {
    const actual = runCase(c).expect;
    for (const k of Object.keys(c.expect)) {
      expect(actual[k], `${c.id}.${k} (${c.note || "no reason given"})`).toEqual(c.expect[k]);
    }
  });
});
